site_name: Tharun Sebastian – Portfolio
repo_url: https://github.com/Tharun135/Tharun135.github.io
repo_name: Tharun135/Tharun135.github.io


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
  icon:
    repo: fontawesome/brands/github


plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji


nav:
  - Home: index.md
  - Writing Samples:
      - writing/index.md
      - API Doc Sample: writing/sample-api-doc.md
      - Style Guide Extracts: writing/style-guide-extracts.md
  - Projects:
      - projects/index.md
      - Doc Scanner (NLP + Flask): projects/docscanner.md
      - DevOps Pipeline Automation: projects/devops-pipeline.md
  - About: about.md
  - Contact: contact.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Tharun135
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/your-profile/
